#!/usr/bin/env bash
# Download base models + raw datasets used by the SFT pipeline into sft/assets/.
# Run from inside the activated venv (`source .venv/bin/activate`) so the
# huggingface_hub `hf` CLI is on PATH.
# Needs HF_TOKEN env (read for public, write for push later).
set -euo pipefail

# Operate from sft/ regardless of where this script was invoked from.
cd "$(dirname "$0")/.."
mkdir -p assets

if ! command -v hf >/dev/null 2>&1; then
  echo "ERROR: hf CLI not on PATH. Activate the venv first: source .venv/bin/activate"
  exit 1
fi

if [ -z "${HF_TOKEN:-}" ]; then
  echo "WARNING: HF_TOKEN not set. Public CoSER data + Qwen base should still pull, but push later will fail."
fi

# Base models
hf download Qwen/Qwen2.5-3B-Instruct        --local-dir assets/Qwen2.5-3B-Instruct
hf download Qwen/Qwen3-4B-Instruct-2507     --local-dir assets/Qwen3-4B-Instruct-2507  # best base for SFT
hf download meta-llama/Llama-3.2-3B-Instruct --local-dir assets/Llama-3.2-3B-Instruct  # gated; needs token

# Datasets (raw — preprocessing scripts under data/ produce sft_chai_*.json)
hf download Neph0s/CoSER --repo-type dataset \
    --include "train/sft_conversations_sharegpt.json" --local-dir assets/CoSER
hf download PygmalionAI/PIPPA --repo-type dataset --local-dir assets/PIPPA
hf download Hieunguyenminh/roleplay --repo-type dataset \
    --local-dir assets/Hieunguyenminh-roleplay

# anime v1 / synth datasets are generated by Sonnet workflow / data/gen_synthetic.py
# and committed directly to assets/sft_chai_anime.json and assets/sft_chai_synth.json.

echo "Done. See assets/ for downloaded models + raw datasets."
